on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  release:
    types:
      - released
jobs:
  build:
    strategy:
      matrix:
        os: [ macos-10.15, ubuntu-18.04, windows-2019 ]
        ghc: [ '8.10' ]
        include:
          - os: ubuntu-18.04
            ghc: '8.8'
          - os: ubuntu-18.04
            ghc: '8.6'
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - id: setup-haskell
        uses: actions/setup-haskell@v1
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: '3.2'
      - uses: actions/cache@v2
        with:
          path: ${{ steps.setup-haskell.outputs.cabal-store }}
          key: ${{ matrix.os }}-${{ matrix.ghc }}-${{ hashFiles('caerbannog.cabal') }}
          restore-keys: ${{ matrix.os }}-${{ matrix.ghc }}-
      - run: cabal test --test-show-details direct
      - run: cabal sdist
      - uses: actions/upload-artifact@v2
        with:
          path: dist-newstyle/sdist/caerbannog-*.tar.gz
          name: caerbannog-${{ matrix.os }}-ghc-${{ matrix.ghc }}-${{ github.sha }}.tar.gz
      - if: matrix.os == 'ubuntu-18.04' && matrix.ghc == '8.10' && github.event_name == 'release' && github.event.action == 'released'
        run: cabal upload --username fozworth --password ${{ secrets.HACKAGE_PASSWORD }} "dist-newstyle/sdist/caerbannog-*.tar.gz"
